Repository micromark/micromark, pull requests merged in 2020-11, with the labels that each got.

#34 types: skip lib check
  tsconfig.json
Labels: ☂️ area/types, 🐢 platform/node, 👶 semver/patch, 🕸️ area/tests

#28 Replace `browserify` with `rollup`
  lib/tokenize/block-quote.js
  lib/tokenize/list.js
  package.json
  rollup.config.js
Labels: 🏗 area/tools, 🔍 status/open

#35 Add es modules support
  buffer.js
  buffer.mjs
  index.js
  index.mjs
  lib/compile/html.js
  lib/constant/constants.d.ts
  lib/constant/constants.js
  lib/tokenize/character-reference.js
  package.json
  rollup.config.js
  rollup.config.mjs
  script/babel-transform-constants.mjs
  script/babel-transform-undebug.mjs
  script/generate-constant-typings.mjs
  script/generate-expressions.js
  script/generate-expressions.mjs
  stream.js
  stream.mjs
  test/babel-transform-constants.mjs
  test/babel-transform-undebug.mjs
  test/commonmark.mjs
  test/extension.mjs
  test/index.mjs
  test/io/content/definition.mjs
  test/io/document/block-quote.mjs
  test/io/document/list-item.mjs
  test/io/flow/code-fenced.mjs
  test/io/flow/code-indented.mjs
  test/io/flow/heading-atx.mjs
  test/io/flow/heading-setext.mjs
  test/io/flow/html.mjs
  test/io/flow/thematic-break.mjs
  test/io/misc/bom.mjs
  test/io/misc/buffer.mjs
  test/io/misc/constants.mjs
  test/io/misc/dangerous-html.mjs
  test/io/misc/dangerous-protocols.mjs
  test/io/misc/default-line-ending.mjs
  test/io/misc/line-ending.mjs
  test/io/misc/nul.mjs
  test/io/misc/tab.mjs
  test/io/misc/url.mjs
  test/io/text/autolink.mjs
  test/io/text/character-escape.mjs
  test/io/text/character-reference.mjs
  test/io/text/code.mjs
  test/io/text/emphasis.mjs
  test/io/text/hard-break.mjs
  test/io/text/html.mjs
  test/io/text/image.mjs
  test/io/text/link-reference.mjs
  test/io/text/link-resource.mjs
  test/io/text/soft-break.mjs
  test/io/text/text.mjs
  test/stream.mjs
  test/util/chunked-splice.mjs
Labels: 🗄 area/interface, 🥂 status/merged, 🦋 type/enhancement, 🧒 semver/minor
