Repository micromark/micromark, pull requests merged in 2023-03, with the labels that each got.

#137 Fix exception in internal `sliceSerialize` API
  packages/micromark/dev/lib/create-tokenizer.js
  test/misc/index.js
  test/misc/slice-chunks.js
Labels: 🐛 type/bug, 🏡 area/internal, 🤞 phase/open

#140 Refactor to improve performance of `now`
  packages/micromark/dev/lib/create-tokenizer.js
  test/perf.js
Labels: 🤞 phase/open

#142 Update `typescript`
  package.json
  packages/micromark-core-commonmark/dev/lib/autolink.js
  packages/micromark-core-commonmark/dev/lib/blank-line.js
  packages/micromark-core-commonmark/dev/lib/character-escape.js
  packages/micromark-core-commonmark/dev/lib/hard-break-escape.js
  packages/micromark-core-commonmark/dev/lib/line-ending.js
  packages/micromark-core-commonmark/dev/lib/thematic-break.js
  test/extension.js
Labels: ☂️ area/types, 🤞 phase/open

#143 Add `exactOptionalPropertyTypes` to `tsconfig.json`
  packages/micromark-util-resolve-all/index.js
  packages/micromark-util-types/index.js
  tsconfig.json
Labels: ☂️ area/types, 🤞 phase/open
